version: "3.7"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BROKER_URL: redis://redis:6379
      C_FORCE_ROOT: "true"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  celery_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BROKER_URL: redis://redis:6379
      C_FORCE_ROOT: "true"
    depends_on:
      - redis
    volumes:
      - ./:/app
    command: celery worker -A app.worker.celery_tasks --loglevel=info --task-events
  redis:
    image: redis
    ports:
      - "6379:6379"
  flower:
    image: mher/flower:0.9.5
    command: ["flower", "--broker=redis://redis:6379", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
